"""Add provider reference ID to recovery attempts

Revision ID: 5b7acbf0eff8
Revises: cc733f1af4c1
Create Date: 2026-08-29 12:13:50.653108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b7acbf0eff8'
down_revision: Union[str, Sequence[str], None] = 'cc733f1af4c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_attempts', sa.Column('provider_reference_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_recovery_attempts_provider_reference_id'), 'recovery_attempts', ['provider_reference_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recovery_attempts_provider_reference_id'), table_name='recovery_attempts')
    op.drop_column('recovery_attempts', 'provider_reference_id')
    # ### end Alembic commands ###
