"""Add Razorpay payment ID

Revision ID: 7a093e77add5
Revises: ba798993ea6a
Create Date: 2026-08-28 16:36:42.983175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a093e77add5'
down_revision: Union[str, Sequence[str], None] = 'ba798993ea6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_payments_razorpay_payment_id'), 'payments', ['razorpay_payment_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_razorpay_payment_id'), table_name='payments')
    op.drop_column('payments', 'razorpay_payment_id')
    # ### end Alembic commands ###
